on:
  workflow_dispatch:
    inputs:
      command:
        description: 'az cli command to execute'
        type: string
        default: 'echo "hello world'
        required: true
      runner:
        description: 'runner'
        type: string
        default: 'ubuntu-latest'
        required: true

name: AzureCLITest

jobs:
  az-cli-test:
    runs-on: ${{ github.event.inputs.runner }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run command
      run: |
        ${{ github.event.inputs.command }}
