on:
  workflow_dispatch:
    inputs:
      command:
        description: 'az cli command to execute'
        type: string
        default: 'echo "hello world'
        required: true
      runner:
        description: 'runner'
        type: string
        default: 'ubuntu-latest'
        required: true

name: AzureCLITest

jobs:
  config:
    runs-on: ${{ github.event.inputs.runner }}
    outputs:
      subscriptions: ${{ steps.read-config.outputs.subscriptions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read Config
        id: read-config
        run: |
          SUBSCRIPTIONS=$(yq -o=json '.' subscriptions.yaml | jq -c .subscriptions)
          echo ::set-output name=subscriptions::${SUBSCRIPTIONS}


  loop-subscriptions:
    runs-on: ${{ github.event.inputs.runner }}
    needs:
      - config
    strategy:
      matrix:
        subscription: ${{ fromJSON(needs.config.outputs.subscriptions) }}
    steps:
    - name: Run command
      run: |
        echo ${{ matrix.subscription.name }}
        echo ${{ matrix.subscription.environments }}
