on:
  workflow_dispatch:
    inputs:
      command:
        description: 'az cli command to execute'
        type: string
        default: 'echo "hello world"'
        required: true

name: AzureCLITest

jobs:
  az-cli-test:
    runs-on: self-hosted
    steps:
    - name: Run command
      run: |
        ${{ github.event.inputs.command }}
